name: Test setup-hdfs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-setup-hdfs:
    name: Test setup HDFS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        hdfs-version: [ "2.10.1", "3.2.3", "3.3.1", "3.3.2" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: npm install
        run: npm install

      - name: Run setup-hdfs ${{ matrix.hdfs-version }}
        uses: ./
        with:
          hdfs-version: ${{ matrix.hdfs-version }}

      - name: Test hadoop home
        run: echo ${{env.HADOOP_HOME}}

      - name: Check hdfs
        run: curl ${{env.HDFS_NAMENODE_ADDR}}

      - name: Check webhdfs
        run: curl ${{env.HDFS_NAMENODE_HTTP_ADDR}}/webhdfs/v1/?op=LISTSTATUS
